#!/bin/bash

mkdir -p out

printf "Enter the servers FQDN (e.g. myserver.com): "
while read FQDN; do
    if [[ $FQDN =~ ^(\*\.)?([a-z-]+\.)+[a-z-]+$ ]]; then
	break
    else
	echo "  Wrong format! Please try again.."
	printf "Enter the servers FQDN (e.g. myserver.com): "
    fi
done

echo "You've entered : $FQDN"

printf "Enter your organization name (O): [My Company] "
read O
[ -z $O ] && O="My Company"
echo $O

printf "Enter your Locality (L): [Bern] "
read L
[ -z $L ] && L="Bern"
echo $L

printf "Enter your State or Province (ST): [BE] "
read ST
[ -z $ST ] && ST="BE"
echo $ST

printf "Enter your Country (C): [CH] "
read C
[ -z $C ] && C="CH"
echo $C

printf "Enter a domain ALIAS (e.g. *.myserver.com): "
ALTNAMES="DNS:$FQDN"
while read INPUT; do
    if [ -z $INPUT ]; then
	echo "break?"
	break
    else
	if [[ $INPUT =~ ^(\*\.)?([a-z-]+\.)+[a-z-]+$ ]]; then
	    ALTNAMES="$ALTNAMES,DNS:$INPUT"
	    echo "Added DNS:$INPUT"
	else 
	    echo "Wrong format!"
	fi

	printf "Enter another domain ALIAS (e.g. myserver2.iwi.unibe.ch): "
    fi
done
sed "s/### FQDN ###/$FQDN/g; s/### O ###/$O/g; s/### ALTNAMES ###/$ALTNAMES/g; s/### C ###/$C/g; s/### L ###/$L/g; s/### ST ###/$ST/g;" < request.cnf > out/$FQDN.cnf

openssl req \
    -new \
    -nodes \
    -keyout "out/$FQDN.key" \
    -config out/$FQDN.cnf \
    -out "out/$FQDN.csr"

